name: postgis
type: db
icon: postgis
from: postgres
fromVersionConstraint: "^1.0.0"
fromVersion: "1.0.0"
title: PostGIS

options:
- version: '18'
  tag: '18-postgis-1.40.0'

labels:
- postgis
- postgres
- postgresql
